version: 2.1

jobs:
  build:
    macos:
      xcode: 10.1.0
    steps:
      - checkout
      - run: 
          name: Setup
          command: |
          pip3 install --upgrade pip
          cd $CIRCLE_PROJECT_REPONAME
          pip3 install .