version: 2.1

jobs:
  build:
    macos:
      xcode: 10.1.0
    steps:
      - checkout
      - run: 
          name: Setup
          command: |
          pip3 install --upgrade pip
          cd $CIRCLE_PROJECT_REPONAME
          pip3 install .

workflows:
  version: 2
  dev_stage_pre-prod:
    jobs:
      - test_dev:
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - dev
