 name: sync to gitee
 on:
   push:

 jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
     - uses: actions/checkout@v2
       with:
         fetch-depth: 0
         run: |
              git config --global --add safe.directory /github/workspace
     - uses: acefei/sync-repo-action@master
       with:
         ssh_private_key: ${{ secrets.GITEE_KEY }}
         target_repo: ssh://git@gitee.com/qilingframework/qiling.git
         
